### ISSUE TITLE
Take a look at the changed shooter code

### ISSUE THREAD

**Issue by stlgolfer** [blabel3/MicdsRobotics#10]
I changed the shooter code so that you now only have to press the a button. Once for on, another click for off. Since I can't run the file, would someone take a look to see if it would actualy work? Thanks

**Comment by blabel3** [comment]
I gotchu fam
The else part in your if loop would've ran as long as they weren't holding the a button, so it would've almost always set the power to 0. I changed it so that the a button toggles shooterState and then just tied the power to that. It should work how you intended it now. :) Changes here #11 
Also I'm trying to learn pull requests and real github workflows so yeah that's half of what this was about.
